import type { CompoundSavingsVariant } from "./CompoundSavings_Calculator";

export const COMPOUND_VARIANTS: Record<string, CompoundSavingsVariant> = {
  savings: {
    idPrefix: "savings",
    hint: "Monthly deposits with compound growth (US savings account estimate).",
    defaultInitial: "1000",
    defaultMonthly: "200",
    defaultRate: "4.5",
    defaultYears: "10",
    buttonLabel: "Calculate savings",
  },
  investment: {
    idPrefix: "invest",
    hint: "Lump sum plus monthly investing.",
    defaultInitial: "10000",
    defaultMonthly: "500",
    defaultRate: "7",
    defaultYears: "20",
    buttonLabel: "Calculate growth",
  },
  retirement: {
    idPrefix: "retire",
    hint: "401(k)/IRA-style growth with monthly contributions.",
    defaultInitial: "50000",
    defaultMonthly: "500",
    defaultRate: "6",
    defaultYears: "25",
    buttonLabel: "Project retirement balance",
  },
  "401k": {
    idPrefix: "401k",
    hint: "Employer plan growth — enter your expected return and contributions.",
    defaultInitial: "25000",
    defaultMonthly: "600",
    defaultRate: "6.5",
    defaultYears: "30",
    buttonLabel: "Calculate 401(k) balance",
  },
  "roth-ira": {
    idPrefix: "roth",
    hint: "Roth IRA future value (tax-free growth not modeled separately).",
    defaultInitial: "5000",
    defaultMonthly: "500",
    defaultRate: "6",
    defaultYears: "30",
    buttonLabel: "Calculate Roth balance",
  },
  cd: {
    idPrefix: "cd",
    hint: "Certificate of deposit — lump sum, no monthly additions.",
    showMonthlyContribution: false,
    defaultInitial: "10000",
    defaultMonthly: "0",
    defaultRate: "4.5",
    defaultYears: "5",
    buttonLabel: "Calculate CD value",
  },
  "future-value": {
    idPrefix: "fv",
    showMonthlyContribution: false,
    defaultInitial: "5000",
    defaultMonthly: "0",
    defaultRate: "5",
    defaultYears: "10",
    buttonLabel: "Calculate future value",
  },
  "compound-interest": {
    idPrefix: "compound",
    showMonthlyContribution: false,
    defaultInitial: "10000",
    defaultMonthly: "0",
    defaultRate: "5",
    defaultYears: "10",
    buttonLabel: "Calculate compound interest",
  },
};
